- redéfinir les function de base
- message d'attente de chargement
- couleur des liens pendant leur exécution
- $view not set (quand Domain affiche :Liste, par exemple)
- UI user_right (cf helpers.php)
- exportation / importation (noeuds avec commentaires, ... + fichiers)
- taille de l'éditeur php
- purge de edQ/tmp
- purger les répertoires vides une fois que la sous-variable est supprimée