- redéfinir les function de base
- message d'attente de chargement
- couleur des liens pendant leur exécution
- $view not set (quand Domain affiche :Liste, par exemple)
- UI userRight (cf helpers.php)
- purge de edQ/tmp